version: '3.8'
networks:
  net:
    driver: overlay
    attachable: true
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html:ro
    networks:
      - net
